// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWSTjAC7JerV-dTj2maYwyQ5tKoepLhvk',
    appId: '1:874442787392:web:fe3e40456cadb19ed22da5',
    messagingSenderId: '874442787392',
    projectId: 'module2-39e66',
    authDomain: 'module2-39e66.firebaseapp.com',
    storageBucket: 'module2-39e66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3-dbYJNaDg28Z1QnzFiIgHqP1tkAf360',
    appId: '1:874442787392:android:d0f35f606e5c4e9fd22da5',
    messagingSenderId: '874442787392',
    projectId: 'module2-39e66',
    storageBucket: 'module2-39e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSv9wBFCPvTMxO9i_t0CU8YyZo_jWrK8s',
    appId: '1:874442787392:ios:cdd71521df4f8762d22da5',
    messagingSenderId: '874442787392',
    projectId: 'module2-39e66',
    storageBucket: 'module2-39e66.appspot.com',
    iosBundleId: 'com.example.module2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSv9wBFCPvTMxO9i_t0CU8YyZo_jWrK8s',
    appId: '1:874442787392:ios:c07be35e9bda08f4d22da5',
    messagingSenderId: '874442787392',
    projectId: 'module2-39e66',
    storageBucket: 'module2-39e66.appspot.com',
    iosBundleId: 'com.example.module2.RunnerTests',
  );
}
